#!/bin/bash

if [[ $EUID -ne 0 ]]; then echo "This script must be run as root" && exit 1; fi
readonly gosrc="https://golang.org/dl/go"
readonly VERSION=${1:-"1.17"}
readonly GO_OOS=${2:-"linux-amd64"}
readonly GO_TAR="$VERSION.$GO_OOS.tar.gz"
readonly GO_URL="$gosrc/$GO_TAR"
export PATH=$PATH:/usr/local/go/bin

wget $GO_URL
rm -rf /usr/local/go /bin/go
tar -C /usr/local -xzf $GO_TAR
rm -rf $GO_TAR

echo -e "\n\n\trun\n\t\texport PATH=\$PATH:/usr/local/go/bin\n\n"

